<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Classic Models - Liste des commandes</title>
    <style>
        table {
            width: 100%;
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <h1>Liste des commandes </h1>

    <nav class="navbar bg-light">
        <div class="container-fluid">
            <form class="d-flex" role="search" method="POST">
                <input class="form-control me-2" type="search" placeholder="Client" aria-label="Search" name="customerName">
                <button class="btn btn-dark" type="submit">Rechercher</button>
            </form>
        </div>
</nav>

    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Numéro</th>
                <th>Nom du client</th>
                <th>Date de commande</th>
                <th>Statut</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($orders as $order) : ?>
                <tr>
                    <td><a href="invoice.php?orderNumber=<?=$order["orderNumber"]?>"> <?=$order["orderNumber"]?> </a></td>
                    <td> <?=$order['customerName']?> </td>
                    <td> <?=$order['orderDate']?> </td>
                    <td> <?=$order['status']?> </td>
                </tr>
            <?php endforeach; ?> 
        </tbody>
    </table>

</body>
</html>