<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Bon de commande</title>
    <style>
        table {
            width: 100%;
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <h1>Bon de commande </h1>
    <p><< <a href='vues/index.phtml'>Retour à la page principale</a> </p>

    <p> <?=$customerDetails['customerName']?> </p>
    <strong><?=$customerDetails['contactLastName'];?> <?=$customerDetails['contactFirstName'];?></strong>
    <p> <?=$customerDetails['addressLine1']?> </p>
    <p> <?=$customerDetails['city']?> </p>
    <p> <?=$customerDetails['country']?> </p>

    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Produit</th>
                <th>Quantité</th>
                <th>Prix Unitaire</th>
                <th>Total</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($orderDetails as $orderDetail): ?>
                <tr>
                    <td> <?=$orderDetail['productName']?> </td>
                    <td> <?=$orderDetail['quantityOrdered']?> </td>
                    <td> <?=$orderDetail['priceEach']?> $</td>
                    <td> <?=$orderDetail['total']?> $</td>
                </tr> 
            <?php endforeach ?> 
        </tbody>
    
        <tfoot>
            
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td> <strong> Montant HT </strong> </td>
                    <td> <?=$HT?> $</td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td> <strong> TVA (20%) </strong> </td>
                    <td> <?=$TVA?> $</td>
                </tr> 
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td> <strong> Montant TTC </strong> </td>
                    <td> <?=$TTC?> $</td>
                </tr>  
            
        </tfoot>
    </table>
    
    
</body>
</html>